[package]
name = "anime-game-core"
version = "0.1.8"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
edition = "2021"

[dependencies]
curl = { version = "0.4" }  # `static-curl` and `static-ssl` for static linking
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
fs_extra = "1.2.0"

# Install feature
uuid = { version = "1.1", features = ["v4", "fast-rng"], optional = true }
zip = { version = "0.6", optional = true }
tar = { version = "0.4", optional = true }

# Compression types for tar
xz = { version = "0.1", optional = true }
bzip2 = { version = "0.4", optional = true }
flate2 = { version = "1.0", optional = true }

# Linux patch feature
md5 = { version = "0.7", optional = true }
# git2 = { version = "0.14.4", optional = true }

# External feature
kinda-virtual-fs = { version = "0.1.1", optional = true }
lazy_static = { version = "1.4.0", optional = true }

[features]
install = ["external", "dep:uuid", "dep:zip", "dep:tar", "dep:xz", "dep:bzip2", "dep:flate2"]
linux-patch = ["dep:md5"] # , "dep:git2"
external = ["dep:kinda-virtual-fs", "dep:lazy_static"]
all = ["install", "linux-patch", "external"]
static = ["curl/rustls", "curl/static-curl"]
