[package]
name = "anime-game-core"
version = "0.1.0"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
edition = "2021"

[dependencies]
curl = { version = "0.4.43", features = ["rustls"] }  # `static-curl` and `static-ssl` for static linking
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
fs_extra = "1.2.0"

# Install feature
uuid = { version = "1.1.2", features = ["v4", "fast-rng"], optional = true }
zip = { version = "0.6.2", optional = true }
tar = { version = "0.4.38", optional = true }

# Compression types for tar
xz = { version = "0.1.0", optional = true }
bzip2 = { version = "0.4.3", optional = true }
flate2 = { version = "1.0.24", optional = true }

# Linux patch feature
md5 = { version = "0.7.0", optional = true }

[features]
install = ["dep:uuid", "dep:zip", "dep:tar", "dep:xz", "dep:bzip2", "dep:flate2"]
linux-patch = ["dep:md5"]
all = ["install", "linux-patch"]
