[package]
name = "animegame-core"
version = "0.1.0"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
edition = "2021"

[dependencies]
fs_extra = "1.2.0"
minreq = { version = "2.6.0", features = ["json-using-serde", "https"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
